apiVersion: crd.antrea.io/v1alpha1
kind: Traceflow
metadata:
  name: test
spec:
  liveTraffic: true
  #droppedOnly: true
  source:    
    pod: pod1
    namespace: default    
  destination:
    service: tf-destination
    namespace: default
  packet:
    ipHeader:
      protocol: 6
    transportHeader:
      tcp:
        dstPort: 80
