apiVersion: ops.antrea.tanzu.vmware.com/v1alpha1
kind: Traceflow
metadata:
  name: tf-pod1-to-pod2-icmp
spec:
  source:    
    pod: pod1
    namespace: default    
  destination:
    pod: pod2
    namespace: default
  packet:
    ipHeader:
      protocol: 1
