apiVersion: crd.antrea.io/v1alpha1
kind: Traceflow
metadata:
  name: tf-pod1-to-pod3
spec:
  source:    
    pod: pod1
    namespace: default    
  destination:
    pod: pod3
    namespace: default
  packet:
    ipHeader:
      protocol: 6
    transportHeader:
      tcp:
        srcPort: 10002
        dstPort: 80
