apiVersion: crd.antrea.io/v1alpha1
kind: Traceflow
metadata:
  name: tf-pod1-to-svc
spec:
  source:    
    pod: pod1
    namespace: default    
  destination:
    service: tf-destination
    namespace: default
  packet:
    ipHeader:
      protocol: 6
    transportHeader:
      tcp:
        dstPort: 80
